# Generated by Django 3.2.14 on 2022-08-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('SlugProject', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=300)),
                ('ProjectTypes', models.CharField(choices=[('DevMob', 'Mobile Application'), ('DevWeb', 'Web Site'), ('Des', 'Design'), ('MarSEO', 'SEO & Marketing'), ('Deb', 'Debuging')], max_length=10)),
                ('Progress', models.CharField(choices=[('Progress', 'In Progress'), ('Done', 'Done'), ('Pend', 'Pending')], max_length=10)),
                ('ClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
        ),
    ]
