# Generated by Django 3.2.15 on 2022-10-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projects_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Description',
        ),
    ]
