# Generated by Django 3.2.15 on 2022-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_projects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Description',
            field=models.CharField(default=123, max_length=300),
            preserve_default=False,
        ),
    ]
