# Generated by Django 3.2.16 on 2022-11-14 14:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
