# Generated by Django 3.2.16 on 2022-11-14 14:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='Name', unique=True, verbose_name='slug'),
        ),
    ]
