# Generated by Django 3.2.14 on 2022-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                # ('Logo', models.CharField(max_length=200)),
                ('Company_name', models.CharField(max_length=200)),
                ('Company_domaine', models.CharField(max_length=200)),
                ('Validated_client', models.BooleanField(default=False)),
            ],
        ),
    ]
