# Generated by Django 3.2.15 on 2022-08-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220818_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
