# Generated by Django 3.2.15 on 2022-08-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_authorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='AuthorId',
            new_name='authorId',
        ),
    ]
