# Generated by Django 3.2.15 on 2022-09-14 11:05

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220914_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Content',
            field=django_quill.fields.QuillField(),
        ),
    ]
