# Generated by Django 3.2.15 on 2022-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='FeatureImage',
            field=models.ImageField(blank=True, default='default-thumb.png', null=True, upload_to='blog/categories//%Y/%m/%d/'),
        ),
    ]
