# Generated by Django 3.2.15 on 2022-10-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20220922_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='FeatureImage',
            field=models.ImageField(blank=True, default='default-thumb.png', null=True, upload_to='blog/categories/%Y/%m/%d/'),
        ),
    ]
