# Generated by Django 3.2.15 on 2022-09-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('Email', models.EmailField(max_length=200, verbose_name='Email')),
                ('Topics', models.CharField(max_length=250, verbose_name='Topics')),
                ('Message', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
