# Generated by Django 3.2.14 on 2022-08-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SlugProject', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=300)),
                ('Delivery_date', models.DateField()),
                ('ProjectTypes', models.CharField(choices=[('Normal', 'Normal'), ('DevWeb', 'Web Site'), ('Des', 'Design'), ('MarSEO', 'SEO & Marketing'), ('Deb', 'Debuging')], max_length=10)),
                ('AssignedTo', models.CharField(choices=[('IT', 'It Services'), ('Marketing', 'Marketing Services'), ('Comm', 'Commercial')], max_length=10)),
                ('ProjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
