# Generated by Django 3.2.15 on 2022-08-18 12:58

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220818_1358'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='Delivery_date',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='SlugProject',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='id',
        ),
        migrations.AddField(
            model_name='tasks',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name', unique_with=('created_at',)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='AssignedTo',
            field=models.CharField(choices=[('ITS', 'It Services'), ('MS', 'Marketing Services'), ('CS', 'Commercial')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Description',
            field=models.CharField(max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='ProjectId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.projects'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='ProjectTypes',
            field=models.CharField(choices=[('Nrml', 'Normal'), ('DW', 'Web Site'), ('Des', 'Design'), ('MSEO', 'SEO & Marketing'), ('Deb', 'Debuging')], max_length=10),
        ),
    ]
